[book]
authors = ["xrMPE"]
language = "ru"
multilingual = false
src = "src"
title = "xrMPE modding book"

[output.html]
git-repository-url = "https://github.com/VadFonker-cyber/xrmpe_book"
edit-url-template = "https://github.com/VadFonker-cyber/xrmpe_book/edit/main/{path}"